- name: 'Baixa o pacote do Worpress {{ wp_version}}'
  get_url:
      url: 'https://wordpress.org/wordpress-{{ wp_version}}.tar.gz'
      dest: '/tmp/wordpress-{{ wp_version}}.tar.gz'
- name: "Descompacta o wordpress"
  unarchive:
    src: '/tmp/wordpress-{{ wp_version}}.tar.gz'
    dest: /var/www
    remote_src: yes
  become: yes

- name: Copia a config de exemplo
  copy:
    src: "{{ wp_install_dir }}/wp-config-sample.php"
    dest: "{{ wp_install_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: Configura o wordpress
  replace:
    path: "{{ wp_install_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'localhost', value: '{{ wp_db_ip }}' }
    - { regex: 'database_name_here', value: '{{ wp_db_name }}' }
    - { regex: 'username_here', value: '{{ wp_db_user }}' }
    - { regex: 'password_here', value: '{{ wp_db_pwd }}' }
  become: yes

- name: Copia a config do Apache
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify: Reinicia apache
